FROM alpine:3.9

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk add libevent mariadb-connector-c libssl1.1 --no-cache && \
    mkdir -p /etc/srp

COPY srps /usr/sbin/
COPY srps.conf /etc/srp/

EXPOSE 511 925

CMD ["/usr/sbin/srps"]